# Generated by Django 5.2.8 on 2025-11-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concursoapp', '0002_question_difficulty_question_source_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.TextField(),
        ),
    ]
